/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as CadastroConfirmacaoRouteImport } from './routes/cadastro.confirmacao'
import { Route as MarketplaceProductIdRouteImport } from './routes/marketplace.$productId'
import { Route as ProdutosNovoRouteImport } from './routes/produtos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroConfirmacaoRoute = CadastroConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => CadastroRoute,
} as any)
const MarketplaceProductIdRoute = MarketplaceProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const ProdutosNovoRoute = ProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/membros': typeof MembrosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel': typeof PainelRoute
  '/pedidos': typeof PedidosRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/suporte': typeof SuporteRoute
  '/cadastro/confirmacao': typeof CadastroConfirmacaoRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/produtos/novo': typeof ProdutosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/membros': typeof MembrosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel': typeof PainelRoute
  '/pedidos': typeof PedidosRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/suporte': typeof SuporteRoute
  '/cadastro/confirmacao': typeof CadastroConfirmacaoRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/produtos/novo': typeof ProdutosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/membros': typeof MembrosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel': typeof PainelRoute
  '/pedidos': typeof PedidosRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/suporte': typeof SuporteRoute
  '/cadastro/confirmacao': typeof CadastroConfirmacaoRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/produtos/novo': typeof ProdutosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/afiliados'
    | '/cadastro'
    | '/checkout'
    | '/como-funciona'
    | '/financeiro'
    | '/login'
    | '/marketplace'
    | '/membros'
    | '/notificacoes'
    | '/painel'
    | '/pedidos'
    | '/planos'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/suporte'
    | '/cadastro/confirmacao'
    | '/marketplace/$productId'
    | '/produtos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/afiliados'
    | '/cadastro'
    | '/checkout'
    | '/como-funciona'
    | '/financeiro'
    | '/login'
    | '/marketplace'
    | '/membros'
    | '/notificacoes'
    | '/painel'
    | '/pedidos'
    | '/planos'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/suporte'
    | '/cadastro/confirmacao'
    | '/marketplace/$productId'
    | '/produtos/novo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/afiliados'
    | '/cadastro'
    | '/checkout'
    | '/como-funciona'
    | '/financeiro'
    | '/login'
    | '/marketplace'
    | '/membros'
    | '/notificacoes'
    | '/painel'
    | '/pedidos'
    | '/planos'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/suporte'
    | '/cadastro/confirmacao'
    | '/marketplace/$productId'
    | '/produtos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AfiliadosRoute: typeof AfiliadosRoute
  CadastroRoute: typeof CadastroRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MembrosRoute: typeof MembrosRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PainelRoute: typeof PainelRoute
  PedidosRoute: typeof PedidosRoute
  PlanosRoute: typeof PlanosRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/confirmacao': {
      id: '/cadastro/confirmacao'
      path: '/confirmacao'
      fullPath: '/cadastro/confirmacao'
      preLoaderRoute: typeof CadastroConfirmacaoRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/marketplace/$productId': {
      id: '/marketplace/$productId'
      path: '/$productId'
      fullPath: '/marketplace/$productId'
      preLoaderRoute: typeof MarketplaceProductIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/produtos/novo': {
      id: '/produtos/novo'
      path: '/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof ProdutosNovoRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface CadastroRouteChildren {
  CadastroConfirmacaoRoute: typeof CadastroConfirmacaoRoute
}

const CadastroRouteChildren: CadastroRouteChildren = {
  CadastroConfirmacaoRoute: CadastroConfirmacaoRoute,
}

const CadastroRouteWithChildren = CadastroRoute._addFileChildren(
  CadastroRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceProductIdRoute: typeof MarketplaceProductIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceProductIdRoute: MarketplaceProductIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ProdutosRouteChildren {
  ProdutosNovoRoute: typeof ProdutosNovoRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosNovoRoute: ProdutosNovoRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AfiliadosRoute: AfiliadosRoute,
  CadastroRoute: CadastroRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MembrosRoute: MembrosRoute,
  NotificacoesRoute: NotificacoesRoute,
  PainelRoute: PainelRoute,
  PedidosRoute: PedidosRoute,
  PlanosRoute: PlanosRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
